# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: ClientComm Product FAQ
subtitle: Code for America 2016 Fellowship

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/clientcomm-faq'

# Author/Organization info to be displayed in the templates
author:
  name: Kuan Butts
  url: http://localhost:4000

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Report Overview
  url: ./
  internal: true
- text: Benefits
  url: benefits/
  internal: true
- text: How do I?
  url: howdoi/
  internal: true
- text: Features
  url: features/
  internal: true
- text: Tips
  url: tips/
  internal: true


# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: ClientComm
  description: Case manager comms
  url: https://github.com/slco-2016/clientcomm
- name: SLCo Budget Explorer
  description: Data visualization tool
  url: https://github.com/slco-2016/slco-budget
- name: SLCo Court Dates
  description: Parses Court VINE data
  url: https://github.com/slco-2016/slco-court-calendar-service
- name: Cal Responder
  description: Fasciltates text message queries
  url: https://github.com/slco-2016/cal-responder
- name: CJS Client Capture
  description: Simple pre-booking registration
  url: https://github.com/slco-2016/cjs_client_capture
- name: Utah Court Dates
  description: Scrapes State Court PDFs
  url: https://github.com/slco-2016/utah-court-calendar-service

# Style Variables
brand_color: "#004b6a"

# Offline caching
offline_cache: false
cache_name: CFA-SALTLAKE-v1.1
